version: '3'
services:
  kafka:
    image: confluentinc/confluent-local:7.5.0
    container_name: kafka
    networks:
      - streaming-data-pipelines-book
    ports:
     - 9092:9092
     - 9093:9093
    environment:
     - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
     - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
     - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
     - KAFKA_LOG_DIRS=/var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
  postgres:
    image: flippingbits/postgres-case-study:latest
    container_name: postgres
    networks:
      - streaming-data-pipelines-book
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    networks:
      - streaming-data-pipelines-book
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    environment:
      - CLICKHOUSE_DB=clickhouse
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  connect:
    image: flippingbits/connect:latest
    container_name: connect
    networks:
      - streaming-data-pipelines-book
    ports:
      - 8083:8083
    links:
      - clickhouse
      - fake-analytics-api
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  fake-analytics-api:
    image: flippingbits/fake-analytics-api:latest
    container_name: fake_analytics_api
    networks:
      - streaming-data-pipelines-book
    ports:
      - 8080:8080

networks:
  streaming-data-pipelines-book:
    name: streaming-data-pipelines-book

volumes:
  kafka-data:
    name: streaming-data-pipelines-book-kafka-data
