---
name       : Build container images
on         :
  push:

permissions:
  packages: write

jobs       :
  verify-files:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v3
    -   name: Verify Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile*
          recursive: true
          verbose: true
          failure-threshold: error
  push_connect_image:
    name: Build and push connect image
    needs: verify-files
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v3
    -   name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: flippingbits
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -   name: Build flippingbits/connect and push it to DockerHub
        working-directory: connect
        run: |
          docker build -t flippingbits/connect:latest -t flippingbits/connect:${GITHUB_SHA} .
          docker push flippingbits/connect:latest
          docker push flippingbits/connect:${GITHUB_SHA}
  push_postgres_image:
    name: Build and push Postgres image
    needs: verify-files
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v3
    -   name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: flippingbits
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -   name: Build flippingbits/postgres-case-study and push it to DockerHub
        working-directory: postgres-case-study
        run: |
          docker build -t flippingbits/postgres-case-study:latest -t flippingbits/postgres-case-study:${GITHUB_SHA} .
          docker push flippingbits/postgres-case-study:latest
          docker push flippingbits/postgres-case-study:${GITHUB_SHA}
  push_fake_analytics_api_image:
    name: Build and push Fake Analytics API image
    needs: verify-files
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v3
    -   name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: flippingbits
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -   name: Build flippingbits/fake-analytics-api and push it to DockerHub
        working-directory: fake-analytics-api
        run: |
          docker build -t flippingbits/fake-analytics-api:latest -t flippingbits/fake-analytics-api:${GITHUB_SHA} .
          docker push flippingbits/fake-analytics-api:latest
          docker push flippingbits/fake-analytics-api:${GITHUB_SHA}
